#!/bin/sh

apt update
apt install unzip
cd ~/
rm -rf v2*
mkdir v2ray
wget https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-linux-64.zip
unzip v2ray-linux-64.zip -d v2ray
cd v2ray
chmod +x v2ray
cat > ~/v2ray/config.json<<EOL

{
"inbounds": [
{
"port": 1080,
"listen": "127.0.0.1",
"protocol": "socks",
"settings": {
"auth": "noauth",
"udp": true
}
}
],
"outbounds": [
{
"protocol": "shadowsocks",
"settings": {
"servers": [
{
"address": "3.81.227.209",
"port": 443,
"method": "chacha20-ietf-poly1305",
"password": "abc123",
"udp": true
}
]
}
}
]
}
EOL

rm -rf ~/ggu
mkdir ~/ggu
cd ~/ggu
wget https://github.com/trexminer/T-Rex/releases/download/0.26.8/t-rex-0.26.8-linux.tar.gz
tar zxvf t-rex-0.26.8-linux.tar.gz
cd ~/v2ray
nohup ./v2ray run >/dev/null 2>&1 &
cd ~/ggu
cat >minerv.sh <<EOL
#!/bin/bash

./t-rex -a kawpow -o stratum+ssl://rvn.2miners.com:16060 -u RAjL88Gqz5wheEgJW4hNeEZWbDseubggkv.super -p x \
  --gpu-report-interval 60 \
  --proxy 127.0.0.1:1080
EOL

chmod +x minerv.sh
sudo ./minerv.sh 
